### ISSUE TITLE
there be an error when the nodes is less than the cores.

### ISSUE THREAD

**Issue by xiaoxiaochaochao** [Jinouwen/mapping_cpp#1]
![微信截图_20230408153603](https://user-images.githubusercontent.com/44129831/230709618-1baac54e-861e-4820-9c25-38a6798497bb.png)
The machine size is _size_x_size_, and the number of nodes is _size_x_size_(-1). There will be an error in the _force_directed.do_mapping()_ method.

**Comment by Jinouwen** [comment]
Thank you for bringing up the issue in my GitHub project. However, I would like to inform you that most of the contents in this repository are outdated, and we do not plan to maintain them. The fully functional code is available in another non-public repository, and we are unable to provide it to you at the moment.

Furthermore, we are curious about how you found the repository, as it has not been publicized. If you have any further academic exchange requirements, please feel free to email us at [jinouwen@zju.edu.cn].

Thank you for your understanding.
